[tasks.install-target-wasm32-unknown-unknown]
command = "rustup"
args = ["target", "install", "wasm32-unknown-unknown"]

[tasks.install-basic-http-server]
install_crate = {crate_name = "basic-http-server", binary = "basic-http-server", test_arg="--help"}

[tasks.install-wasm-pack]
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }

[tasks.build]
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "app", "--out-dir", "target"]
dependencies = ["install-wasm-pack", "install-target-wasm32-unknown-unknown", ]

[tasks.serve]
command = "basic-http-server"
args = ["-x"]
dependencies = ["build", "install-basic-http-server"]

[tasks.test]
disabled = true
